### ISSUE TITLE
Suggestions for RTNeuron 3.0 user guide

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/RTNeuron#1]
I have found some issues related to the RTNeuron 3.0 user guide, located here: https://bbpteam.epfl.ch/documentation/RTNeuron-3.0/user_guide.html

- [x] The `vizcluster` is mentioned without reference. As a user not familiar with the vizcluster I would be confused what is it. Suggestion: Put in a link to a more general description of the vizcluster
- [x] The mention of `vglrun`: What is it? 
- [x] The link to the page 'installations instructions' seems to be broken or not up-to-date
- [x] Typo: Second paragraph in "If you are working in the vizcluster": 'cluter' -> 'cluster'
- [x] Typo: First paragraph in "If you are working in your own machine": 'detais' -> 'details'

**Comment by hernando** [comment]
All items addressed in #12

**Comment by hernando** [comment]
@alex4200 Can we close this issue?
