### ISSUE TITLE
Can't install RT Neuron

### ISSUE THREAD

**Issue by mach512** [BlueBrain/RTNeuron#19]
Hi, 

I am trying to install RT Neuron on Ubuntu with the compilation instructions provided, however I get this error "/home/krishna/Desktop/RTNeuron/Pression/pression/data/liblzf/lzf_c.c:157:5: error: this use of "defined" may not be portable [-Werror=expansion-to-defined]
 #if STRICT_ALIGN
     ^~~~~~~~~~~~"

I have installed all the required packages as asked but could not understand the problem.

**Comment by hernando** [comment]
Could you provide more details about which system and compiler are you using?
Alternatively, you can use the precompiled [AppImage binary](https://github.com/BlueBrain/RTNeuron/releases/download/3.0.0-rc1/rtneuron_x86_64.AppImage) that was uploaded last week. The documentation should be updated to reflect that this binary exists, but this is still a release candidate.

**Comment by hernando** [comment]
That file contains a test of a dependency. If it doesn't compile you can delete the file, reconfigure and build again to skip it.

What do you mean by it doesn't open? An [AppImage](https://appimage.org/) is not an archive like zip, it's supposed to work as a self-contained executable. Maybe you forgot to make it executable after downloading it (in a shell `chmod +x rtneuron_x86_64.AppImage`). If after doing that you still get an error message, please provide precise information about what you are doing and what is the output that you get.

**Comment by mach512** [comment]
Hi, 

I am unable to download the rtneuron_x86_64.AppImage from the link you have sent to me. When I try to download, either it fails or the page doesn't load. 

Is it possible for you to send me the binary via email (mach512@gmail.com)?  

Thank you.

**Comment by hernando** [comment]
That's strange, try from here then: https://github.com/BlueBrain/RTNeuron/releases
I can't send 200 MB by e-mail (and I wouldn't workaround something that should just work either).

**Comment by mach512** [comment]
This is really strange. I could download zip and tar files from the link you have sent but not the AppImage binary. I do not understand what is the problem. Is it my system or the source, I have no clue? 

Anyways, I think I am able to continue with the installation after you told me to delete the file and reconfigure. That seems to work for now. 

Thank you.

**Comment by hernando** [comment]
Thats's really strange. Are you behind a firewall? Try doing it from the command line:

    wget https://github.com/BlueBrain/RTNeuron/releases/download/3.0.0-rc1/rtneuron_x86_64.AppImage

**Comment by mach512** [comment]
This is the error message 

> Resolving github-production-release-asset-2e65be.s3.amazonaws.com (github-production-release-asset-2e65be.s3.amazonaws.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘github-production-release-asset-2e65be.s3.amazonaws.com’

**Comment by hernando** [comment]
Try later, that seems to be a transient network failure that doesn't have anything to do with your system. It's very strange that it works for me on the other hand.

**Comment by mach512** [comment]
Sure. will give it a try after some time. After compiling, make and make install, launching RTNeuron from command line shows this message 

> krishna@KrishVB:~$ rtneuron
Traceback (most recent call last):
  File "/usr/bin/rtneuron", line 53, in <module>
    import rtneuron
  File "/usr/lib/python3/dist-packages/rtneuron/__init__.py", line 37, in <module>
    from ._rtneuron import *
ImportError: libhdf5.so.101: cannot open shared object file: No such file or directory

I could launch RTNeuron from build/bin without this error.

**Comment by mach512** [comment]
I am extremely sorry. This is a trivial error. I could export the build/bin/rtneuron executable and run it directly from command line. 

Thanks a lot again.
