### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/RTNeuron#2]
The documentation at http://bluebrain.github.io/RTNeuron-3.0/compilation.html requires some updates and clarification: 

 - Clean up dependencies. 
 - Make sure what really is required to install RTNeuron, and what must be installed manually:
  - cmake version 3.0.0
  - sphinx 1.3 (other version for BB5 or something?)
  - lxml

**Comment by hernando** [comment]
I think #11 addresses all this issues

**Comment by hernando** [comment]
@alex4200 can we close this issue?
