### ISSUE TITLE
RTNeuron working

### ISSUE THREAD

**Issue by mach512** [BlueBrain/RTNeuron#20]
Hi, 

Does RTNeuron support external models? I see that there is a requirement for blue brain project config file for the first argument in display_circuit command of RTNeuron. 

I have detailed models in NEURON. Is it not possible to use them with RTNeuron?

**Comment by hernando** [comment]
RTNeuron has limited support for [SONATA](https://github.com/AllenInstitute/sonata). Different people are working on providing support for converting circuit models from other description languages and formats into SONATA: NeuroML, PyNN and NetPyNE. [BMTK](https://github.com/AllenInstitute/bmtk) also allows you to build and simulate networks where the circuit and simuation output are written in SONATA fomat.
