### ISSUE TITLE
start_app() opens a window which doesn't react to input

### ISSUE THREAD

**Issue by hernando** [BlueBrain/RTNeuron#22]
Launching a use-case app from the command line sets up the Qt5 hook to integrate the QT event loop in the IPython shell event loop. However this setup is not done when the IPython console is started first and `start_app()` is called from there. The workaround is to type `%gui qt5` in the console, but this should be done automatically by `start_app`.

**Comment by alex4200** [comment]
@hernando I tried to run the app-image on my private Ubuntu 18.04.1 laptop, bt I get the following error message:

`OSError: lixX11.so cannot open shared object file: No such file or directory`

**Comment by hernando** [comment]
`lixX11.so`? I'd find some logic in the error if it was `libX11.so` with b. The reason may be that Ubuntu 18.04 is using Wayland by default and libX11 doesn't exists. That's a bit surprising nonetheless, as I would expect an emulated X Server to still be present for applications that need it. You can try logging in using "Ubuntu on Xorg" in the greeter or install and configure XWayland.

**Comment by alex4200** [comment]
@hernando My bad: Yes it is `libX11.so`. It is a typo. 

I will try to look into that a bit more based on your comments.

**Comment by alex4200** [comment]
@hernando I managed to install the missing libraries and was able to start `rtneuronApp` on Ubuntu 18.04.1.

I noticed , like in the case above, `start_app()` alone opens a window that does not react. Using `%gui qt5` before solves this problem.

**Comment by hernando** [comment]
The cause of that problem is identified, but I haven't found the solution yet.
