### ISSUE TITLE
Options without functions?

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/RTNeuron#27]
I see two additional options on the screen: Extra models and Cell dyes. 

They are neither documented, nor do they seem to do anything. Can they be taken out, or is there a plan to implement these options?

**Comment by hernando** [comment]
They do something. What have you tried that makes you think that they are not implemented?

**Comment by alex4200** [comment]
I tried to change the color in "Cell dyes" and nothing happened. But Andrew noted to me that I need to have an extra model loaded in order to use this option.

**Comment by hernando** [comment]
Not exactly. You have to type a target name or gid list/range and then press the + button at the right (grayed out until to type something in the line input).

**Comment by alex4200** [comment]
Ok, thanks for the explanation. It seems to work.
