### ISSUE TITLE
Meshes and models tutorial seems to be out of date

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/RTNeuron#3]
In the "Meshes and models" tutorial http://bluebrain.github.io/RTNeuron-3.0/python/meshes_and_models.html it looks like some items are out of date.

In the second-to-last code block you have the following line of code:

`scene.addMesh(numpy.array(vertices), numpy.array(indices), colors=[1, 1, 1, 1], attributes=attributes)`

which generates the following error:

`AttributeError: 'Scene' object has no attribute 'addMesh'`. 

According to the documentation a scene has no method `addMesh`...

**Comment by hernando** [comment]
This is already mentioned in #9 and has been fixed in #11.
