### ISSUE TITLE
Saving images from the RTNeuron ipython prompt

### ISSUE THREAD

**Issue by anirban6908** [BlueBrain/RTNeuron#32]
Hi @hernando,
RTNeuron is finally working once I moved my graphics to the NVidia graphics card. But I can't save the images using 
`view.snapshot('5_neuron.png')
`
 I am getting the error 
`Error writing file 5_neuron.png: Warning: Could not find plugin to write image to file "5_neuron.png".
`
Is it looking for the OSG plugin? I haven't tried the latest app image. Is it fixed there? You mentioned you uploaded the latest app image on the repo - but on the release page version is from December 14. Can you please point me where it is? Or do I have to build the image using docker?  

Thanks

**Comment by hernando** [comment]
Hi @anirban6908, I forgot to answer you about this issue last week. I can confirm you the reproducibility of this problem. I have fixed it for png, but not yet for other file formats. Once it's fixed for all, I'll upload a new AppImage.

**Comment by hernando** [comment]
Sorry for the delay, I was waiting for #34 to be merged before uploading a new AppImage. Now it should be possible to write png, jpeg, tiff and a few other file formats.

**Comment by anirban6908** [comment]
So I just need to run the dockerfile to build the appImage right?

Thanks

**Comment by hernando** [comment]
You can download the AppImage directly from here https://github.com/BlueBrain/RTNeuron/releases/download/3.0.0-rc1/rtneuron_x86_64.AppImage. If you want to build it yourself, you need to build the Docker image and run a  container instance to do it.

**Comment by anirban6908** [comment]
Got it.
Thanks
