### ISSUE TITLE
No graphics shown when AppImage is double-clicked

### ISSUE THREAD

**Issue by probonopd** [BlueBrain/RTNeuron#36]
When the AppImage is double-clicked, no GUI is shown. RTNeutron should either show a default (example) image when invoked without command line parameters, or `Terminal=true` should be set in the desktop file to indicate that this is a command line tool rather than a GUI application.

Reference:
https://github.com/AppImage/appimage.github.io/pull/1302

**Comment by hernando** [comment]
Thanks for the tip. In fact, RTNeuron is a command line tool but it provides multiple GUI apps, however they need to be explicitly requested from the command line. It would be nice to open the default GUI when the desktop icon is double-clicked, is there any way to detect this condition from the AppRun script?

**Comment by hernando** [comment]
I've been experimenting with `Terminal=true` and there's something that doesn't work as I expected. After setting the parameter in the desktop file I was expecting a terminal window to pop up when I double-click on the AppImage file, however it doesn't. I've tried extracting the AppImage, and after fixing the desktop file to point to the actual location of the extracted AppRun script, it behaves as I expected.

**Comment by probonopd** [comment]
> I've been experimenting with `Terminal=true` and there's something that doesn't work as I expected. After setting the parameter in the desktop file I was expecting a terminal window to pop up when I double-click on the AppImage file, however it doesn't.

This only works if the AppImage is launched through its desktop file, which needs to be integrated into the system e.g., using the optional [appimaged](https://github.com/AppImage/appimaged) daemon or [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher).

Is a download with `Terminal=true` available? Then I can re-run our automated tests on it. Thanks.

**Comment by hernando** [comment]
> It would be nice to open the default GUI when the desktop icon is double-clicked, is there any way to detect this condition from the AppRun script?

Is there anything I can do about this?

**Comment by probonopd** [comment]
If RTNeutron is launched without any command line arguments, show some default GUI demo?

**Comment by hernando** [comment]
Yes, but only when double-clicking on the icon.
Nevermind, I find a way to make it behave as I was thinking. Now a default GUI app is shown when double clicking and a prompt is shown when running it from the command line.

**Comment by hernando** [comment]
I've already updated the AppImage above.
