### ISSUE TITLE
Feature: Install and activate RTNeuron 3.0 in BB5

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/RTNeuron#5]
Install and activate RTNeuron 3.0 in BB5. 

If that has been done, testing can continue on the new system...

**Comment by hernando** [comment]
The application is ready for deployment and there's a PR for that. However, there is an issue with the Nvidia driver that I can't resolve myself.

**Comment by hernando** [comment]
The application has been finally deployed, however I didn't have the time to look into a critical bug in the QML GUI for opening circuits.

The module to load is nix/viz/rtneuron

**Comment by alex4200** [comment]
@hernando 

I tried the following steps to start rtneuron on BB5:

1. ssh adietz@bbpv1.epfl.ch
2. salloc --account=proj64 --partition=interactive  --gres=gpu:1 --startx
3. module load nix/viz/rtneuron
4. rtneuron

But I got an error `ImportError: No module named site`.

**Comment by hernando** [comment]
Looks like an environment problem. Try doing module purge before load.

There are some other issues, once is something new.
- Once you have the allocated node, you have to connect to it from another console with vglconnect. Another option to simplify all the steps is to use vizsh, just sudo apt-get install it in your desktop.
- Then you have to launch rtneuron with vglrun (I'd like to get rid of vglrun, but it doesn't seem to be trivial with nix)
- Last, but not least, you need to add --eq-layout Simple to the command to start rtneuron. This is a side effect of a configuration detail in the cluster that needs to be addressed.

**Comment by alex4200** [comment]
I tried to do 

`vglconnect r2i3n0.bbp.epfl.ch`
`vglconnect adietz@r2i3n0.bbp.epfl.ch`

from my local computer, but in both cases the login/connect seems to hang. Am I missing something?

**Comment by hernando** [comment]
First time ssh connections to the nodes take a long time sometimes (~ 1 min), just be patient. I also drop the domain name part and use the hostname only, but I don't know if that makes a difference.

**Comment by hernando** [comment]
Looks like an environment problem. Try doing module purge before load.

There are some other issues, once is something new.
- Once you have the allocated node, you have to connect to it from another console with vglconnect. Another option to simplify all the steps is to use vizsh, just sudo apt-get install it in your desktop.
- Then you have to launch rtneuron with vglrun (I'd like to get rid of vglrun, but it doesn't seem to be trivial with nix)
- Last, but not least, you need to add --eq-layout Simple to the command to start rtneuron. This is a side effect of a configuration detail in the cluster that needs to be addressed.

**Comment by alex4200** [comment]
Login and running on BB5 now works.
